# Generated by Django 3.2.4 on 2021-06-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'invited'), ('declined', 'declined'), ('started', 'started'), ('finished', 'finished')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure1', models.CharField(blank=True, choices=[('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spok', 'spok')], max_length=12, null=True)),
                ('figure2', models.CharField(blank=True, choices=[('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spok', 'spok')], max_length=12, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
        ),
    ]
